### ISSUE TITLE
Problem with phased genotypes

### ISSUE THREAD

**Issue by BELKHIR** [JimWhiting91/genotype_plot#1]
Hi,

In line 139 you separate genotypes into alleles with the function "separate" and use the "/" as separator.
This will not work for phased genotypes where the 2 alleles are separated with "|".

May be a solution is to not use a sep at all, this will use the default value which is a regular expression that matches any sequence of non-alphanumeric values ?

Regards,

Khalid BELKHIR

**Comment by JimWhiting91** [comment]
Thanks Khalid, we have a variant of the function specifically for plotting phased VCFs that handles this. The other benefit of 
having a function specifically for phased vcfs is that there we can either plot a single haplotype with hom het sites or plot multiple rows per individual and plot both haplotypes without het sites. I'll be adding this in the near future.

The benefit of converting genotypes into numeric values is to facilitate clustering with hclust and a numeric distance matrix. 

In the meantime, your suggestion should work, but I've replaced line 139 with:
separate(GT, c("x1", "x2"), "[|/]")

This separates genotypes by either "|" or "/", so should work as expected for phased vcfs with 0|0 format and also allow clustering.

Cheers,
Jim

**Comment by BELKHIR** [comment]
Many thanks !
