### ISSUE TITLE
Clustering method

### ISSUE THREAD

**Issue by BELKHIR** [JimWhiting91/genotype_plot#3]
Hi Jim,

The clustering method used here seems to be based on the hclust procedure applied to a matrix distance.
This distance matrix is calculated from an object returned by the vcfR function extract.gt.
This function when called with as.numeric = TRUE seems to just return the first allele of each genotype :
data(vcfR_test)
extract.gt(vcfR_test)
               NA00001 NA00002 NA00003
rs6054257  "0|0"   "1|0"   "1/1"  
20_17330   "0|0"   "0|1"   "0/0"  
rs6040355  "1|2"   "2|1"   "2/2"  
20_1230237 "0|0"   "0|0"   "0/0"  
microsat1  "0/1"   "0/2"   "1/1"

extract.gt(vcfR_test, as.numeric=T)
                NA00001 NA00002 NA00003
rs6054257        0       1       1
20_17330         0       0       0
rs6040355        1       2       2
20_1230237       0       0       0
microsat1        0       0       1

I'm not sure how this can reflect distance between the underlying pairwise genotypes ?

Regards,

Khalid BELKHIR

**Comment by JimWhiting91** [comment]
Hi Khalid,

Thank you for spotting this, you're right that this is not how I expected the genotype matrix to be formatted prior to clustering, and having gone through some of my own data I've confirmed that the function was only taking the first allele, so 0/0 and 0/1 to 0 and 1/1 to 1.

I've gone back and updated the function to behave as expected, now I manually do the transformations of genotypes from 0/0, 0/1 and 1/1 to 0, 1, 2, and then convert this back to the expected matrix and perform distance clustering on this new matrix. So...

```
    # Remake numeric genotype matrix
    geno_matrix <- as.matrix(pivot_wider(genos[,c("index","snp","GT")], names_from = snp, values_from = GT))
    matrix_inds <- geno_matrix[,1]
    geno_matrix <- geno_matrix[,2:ncol(geno_matrix)]
    geno_matrix <- gsub(" ","",geno_matrix)
    colnames(geno_matrix) <- SNP_pos$BP
    rownames(geno_matrix) <- matrix_inds
    class(geno_matrix) <- "numeric"
```

I believe this resolves the bug, and again thank you for spotting!

Cheers,
Jim

**Comment by BELKHIR** [comment]
This can solve the problem.

However recall that this genotype coding (0,1 or 2) is a valid solution if one is dealing with bi-allelic snp.
Misleading results will be obtained for snp with more than 2 Alternative bases : 
genotype code
0/0           0
0/1           1
1/1           2
0/2           2

So samples homozygous for the first alt base will score as heterozygous with ref and a second Alt base. 
If one would use this tool for multi-allelic snp, a best scoring scheme can be based on counting the number of REF bases for each genotype thus : 
genotype code
0/0           2
0/1           1
1/1           0
0/2           1

Cheers,

Khalid

**Comment by JimWhiting91** [comment]
Hi Khalid,

Yes, that's a good point. I'll add a note that currently this only supports vcfs with biallelic snps, and Ill think about how we can support multiallelic vcfs in the future.

Cheers,
Jim

**Comment by BELKHIR** [comment]
Thank's again.
Khalid,
